chore/build/win/dll: Add version number to DLL
to reduce risk of conflict.

diff --git a/.github/actions/build-win/action.yml b/.github/actions/build-win/action.yml
--- a/.github/actions/build-win/action.yml
+++ b/.github/actions/build-win/action.yml
@@ -32,29 +32,56 @@ runs:
     shell: cmd
     run: ${{ github.action_path }}\build-win.cmd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" build-win "${{ inputs.buildType }}" "${{ inputs.flags }}"
   - name: Test for Target
+    id: tgt_exists
     shell: bash
     env:
       TARGET_LIB: build-win/${{ inputs.libName }}.lib
+      NAME_FILE: build-win/${{ inputs.libName }}_FileName.txt
     run: |
-      if [[ ! -f "$TARGET_LIB" ]]; then
+      if [[ -f "$NAME_FILE" ]]; then
+        echo "NameFile=true" >> $GITHUB_OUTPUT
+      elif [[ -f "$TARGET_LIB" ]]; then
+        echo "NameFile=false" >> $GITHUB_OUTPUT
+      else
         echo Expected target build not found: "$TARGET_LIB"
         exit 1
       fi
-  - name: Return Value
-    id: return
+  - name: Return Static Lib
+    if: steps.tgt_exists.outputs.NameFile == 'false'
+    id: return_static
     shell: bash
     env:
       TARGET_LIB: build-win/${{ inputs.libName }}.lib
-      TARGET_PDB1: build-win/${{ inputs.libName }}.pdb
-      TARGET_PDB2: build-win/CMakeFiles/XPMP2.dir/${{ inputs.libName }}.pdb
-      TARGET_DLL: build-win/${{ inputs.libName }}.dll
+      TARGET_PDB: build-win/CMakeFiles/XPMP2.dir/${{ inputs.libName }}.pdb
     run: |
-      echo "lib-file-name=$(echo $TARGET_LIB)" >> $GITHUB_OUTPUT
-      if [[ -f "$TARGET_PDB1" ]]; then
-        echo "pdb-file-name=$(echo $TARGET_PDB1)" >> $GITHUB_OUTPUT
-      elif [[ -f "$TARGET_PDB2" ]]; then
-        echo "pdb-file-name=$(echo $TARGET_PDB2)" >> $GITHUB_OUTPUT
+      echo "lib-file-name=$TARGET_LIB" >> $GITHUB_OUTPUT
+      if [[ -f "$TARGET_PDB" ]]; then
+        echo "pdb-file-name=$TARGET_PDB" >> $GITHUB_OUTPUT
+      fi
+
+  - name: Return DLL
+    if: steps.tgt_exists.outputs.NameFile == 'true'
+    id: return_dll
+    shell: bash
+    env:
+      NAME_FILE: build-win/${{ inputs.libName }}_FileName.txt
+    run: |
+      ARTIFACT_NAME=$(cat $NAME_FILE)
+      TARGET_LIB="build-win/$ARTIFACT_NAME.lib"
+      TARGET_PDB="build-win/$ARTIFACT_NAME.pdb"
+      TARGET_DLL="build-win/$ARTIFACT_NAME.dll"
+      if [[ -f $TARGET_LIB ]]; then
+        echo "lib-file-name=$TARGET_LIB" >> $GITHUB_OUTPUT
+      else
+        echo "Library $TARGET_LIB not found!"
+        exit 1
+      fi
+      if [[ -f "$TARGET_PDB" ]]; then
+        echo "pdb-file-name=$TARGET_PDB" >> $GITHUB_OUTPUT
       fi
       if [[ -f "$TARGET_DLL" ]]; then
-        echo "dll-file-name=$(echo $TARGET_DLL)" >> $GITHUB_OUTPUT
+        echo "dll-file-name=$TARGET_DLL" >> $GITHUB_OUTPUT
+      else
+        echo "Library $TARGET_DLL not found!"
+        exit 1
       fi
